# packages in environment at /shared/home/v_nishanth_artham/local_scratch/anaconda3/envs/prompt:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
beartype                  0.14.1                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
black                     21.4b2                   pypi_0    pypi
blas                      1.0                         mkl  
bottleneck                1.3.4            py37hce1f21e_0  
brotli                    1.0.9                he6710b0_2  
ca-certificates           2023.05.30           h06a4308_0  
cachetools                5.3.1                    pypi_0    pypi
certifi                   2022.12.7        py37h06a4308_0  
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colored                   1.4.4                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
detectron2                0.6+cu113                pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
expat                     2.4.4                h295c915_0  
filelock                  3.12.2                   pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0  
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
future                    0.18.3                   pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gdown                     4.7.1                    pypi_0    pypi
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
google-auth               2.22.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.60.0                   pypi_0    pypi
grpcio                    1.57.0                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      3.8.0                    pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
humanize                  4.6.0                    pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
iopath                    0.1.9                    pypi_0    pypi
joblib                    1.1.1            py37h06a4308_0  
jpeg                      9e                   h7f8727e_0  
keras                     2.11.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
libclang                  16.0.6                   pypi_0    pypi
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.2.0                h2818925_1  
libuuid                   1.0.3                h7f8727e_2  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.9.14               h74e7548_0  
lz4-c                     1.9.3                h295c915_1  
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-base           3.5.1            py37ha18d171_1  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
ml-collections            0.1.1                    pypi_0    pypi
mock                      5.1.0                    pypi_0    pypi
munkres                   1.1.4                      py_0  
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
numexpr                   2.8.1            py37h6abb31d_0  
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37hf524024_2  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cublas-cu12        12.2.5.6                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.2.140                 pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.2.140                 pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.4.25                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.8.0.76                 pypi_0    pypi
openssl                   1.1.1v               h7f8727e_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pcre                      8.45                 h295c915_0  
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
portalocker               2.7.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyqt                      5.9.2            py37h05f1152_2  
pysocks                   1.7.1                    pypi_0    pypi
python                    3.7.13               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.1.2                h7f8727e_1  
regex                     2023.8.8                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.0.2            py37h51133e4_1  
scipy                     1.6.2            py37had2a1c9_1  
seaborn                   0.12.2           py37h06a4308_0  
setuptools                65.6.3           py37h06a4308_0  
simplejson                3.19.1                   pypi_0    pypi
sip                       4.19.8           py37hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_1  
slurm-gpustat             0.0.15                   pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.38.5               hc218d9a_0  
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.11.0                   pypi_0    pypi
tensorflow-addons         0.19.0                   pypi_0    pypi
tensorflow-estimator      2.11.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.33.0                   pypi_0    pypi
tensorflow-metadata       1.12.0                   pypi_0    pypi
tensorrt                  8.6.1.post1              pypi_0    pypi
tensorrt-bindings         8.6.1                    pypi_0    pypi
tensorrt-libs             8.6.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tfds-nightly              4.4.0.dev202201080107          pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0  
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.66.1                   pypi_0    pypi
typed-ast                 1.5.5                    pypi_0    pypi
typeguard                 4.1.2                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing_extensions         4.4.0            py37h06a4308_0  
urllib3                   1.26.16                  pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0  
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.2.5                h7f8727e_1  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  
zstd                      1.5.2                ha4553b6_0  
