_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1 
DATA:
  NAME: "CUB"
  DATAPATH: "/shared/home/v_nishanth_artham/local_scratch/vpt/src/data/CUB_prompt"  #TODO: need to specify here
  NUMBER_CLASSES: 200
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
